version: "3.8"

networks:
    nginx_network:
    internal:

services:
    microcrud-app:
        image: adhocore/phpfpm:8.1
        container_name: microcrud-app
        working_dir: /src
        restart: always
        networks:
            - internal
            - nginx_network
        volumes:
            - '.:/src'
            - './docker/php/overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
    microcrud-nginx:
        image: nginx:alpine
        container_name: microcrud-nginx
        restart: always
        working_dir: /src
        networks:
            - internal
            - nginx_network
        ports:
            - "9049:80"
        volumes:
            - .:/src
            - ./docker/nginx/microcrud.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - microcrud-app
    microcrud-composer:
        image: composer:latest
        container_name: microcrud-composer
        working_dir: /src
        command: update --ignore-platform-reqs
        volumes:
            - .:/src
        restart: on-failure
        depends_on:
            - microcrud-app
